### ISSUE TITLE
a bunch of error messages? Did i do something wrong?

### ISSUE THREAD

**Issue by clavinohou** [kidJaNateTH/Arduinosu#1]
Arduino: 1.8.18 (Windows Store 1.8.55.0) (Windows 10), Board: "Arduino Uno"

In file included from C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:1:0:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.55.0_x86__mdqgnx93n4wtt\libraries\Keyboard\src/Keyboard.h:29:2: warning: #warning "Using legacy HID core (non pluggable)" [-Wcpp]

 #warning "Using legacy HID core (non pluggable)"

  ^~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino: In function 'void setup()':

Osu:11:11: error: 'LED_BUILTIN_TX' was not declared in this scope

   pinMode(LED_BUILTIN_TX,OUTPUT);

           ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:11:11: note: suggested alternative: 'LED_BUILTIN'

   pinMode(LED_BUILTIN_TX,OUTPUT);

           ^~~~~~~~~~~~~~

           LED_BUILTIN

Osu:12:11: error: 'LED_BUILTIN_RX' was not declared in this scope

   pinMode(LED_BUILTIN_RX,OUTPUT);

           ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:12:11: note: suggested alternative: 'LED_BUILTIN'

   pinMode(LED_BUILTIN_RX,OUTPUT);

           ^~~~~~~~~~~~~~

           LED_BUILTIN

Osu:18:3: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

   Keyboard.begin();

   ^~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino: In function 'void KeysPress()':

Osu:39:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.press(KEY_LEFT_CTRL);

       ^~~~~~~~

Osu:39:22: error: 'KEY_LEFT_CTRL' was not declared in this scope

       Keyboard.press(KEY_LEFT_CTRL);

                      ^~~~~~~~~~~~~

Osu:42:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.press('x');

       ^~~~~~~~

Osu:49:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.release(KEY_LEFT_CTRL);

       ^~~~~~~~

Osu:49:24: error: 'KEY_LEFT_CTRL' was not declared in this scope

       Keyboard.release(KEY_LEFT_CTRL);

                        ^~~~~~~~~~~~~

Osu:52:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.release('x');

       ^~~~~~~~

Osu:59:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.press(KEY_LEFT_CTRL);

       ^~~~~~~~

Osu:59:22: error: 'KEY_LEFT_CTRL' was not declared in this scope

       Keyboard.press(KEY_LEFT_CTRL);

                      ^~~~~~~~~~~~~

Osu:62:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.press('z');

       ^~~~~~~~

Osu:67:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.release(KEY_LEFT_CTRL);

       ^~~~~~~~

Osu:67:24: error: 'KEY_LEFT_CTRL' was not declared in this scope

       Keyboard.release(KEY_LEFT_CTRL);

                        ^~~~~~~~~~~~~

Osu:70:7: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

       Keyboard.release('z');

       ^~~~~~~~

Osu:85:5: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

     Keyboard.press('`');

     ^~~~~~~~

Osu:87:5: error: 'Keyboard' not found. Does your sketch include the line '#include <Keyboard.h>'?

     Keyboard.release('`');

     ^~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino: In function 'void Modes(int, bool)':

Osu:118:15: error: 'LED_BUILTIN_TX' was not declared in this scope

       pinMode(LED_BUILTIN_TX,OUTPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:118:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_TX,OUTPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:119:15: error: 'LED_BUILTIN_RX' was not declared in this scope

       pinMode(LED_BUILTIN_RX,OUTPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:119:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_RX,OUTPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:132:15: error: 'LED_BUILTIN_TX' was not declared in this scope

       pinMode(LED_BUILTIN_TX,INPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:132:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_TX,INPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:133:15: error: 'LED_BUILTIN_RX' was not declared in this scope

       pinMode(LED_BUILTIN_RX,INPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:133:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_RX,INPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:139:15: error: 'LED_BUILTIN_TX' was not declared in this scope

       pinMode(LED_BUILTIN_TX,INPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:139:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_TX,INPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:140:15: error: 'LED_BUILTIN_RX' was not declared in this scope

       pinMode(LED_BUILTIN_RX,INPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:140:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_RX,INPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:144:15: error: 'LED_BUILTIN_TX' was not declared in this scope

       pinMode(LED_BUILTIN_TX,INPUT);

               ^~~~~~~~~~~~~~

C:\Users\calvi\AppData\Local\Temp\Temp1_Arduinosu-main.zip\Arduinosu-main\Osu\Osu.ino:144:15: note: suggested alternative: 'LED_BUILTIN'

       pinMode(LED_BUILTIN_TX,INPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

Osu:145:15: error: 'LED_BUILTIN_RX' was not declared in this scope

       pinMode(LED_BUILTIN_RX,INPUT);

               ^~~~~~~~~~~~~~

'LED_BUILTIN'

       pinMode(LED_BUILTIN_RX,INPUT);

               ^~~~~~~~~~~~~~

               LED_BUILTIN

exit status 1

'LED_BUILTIN_TX' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by kidjanate** [comment]
Sorry for being late. Arduino Uno doesn't support the Keyboard library. I suggest using Arduino pro micro or Arduino Leonardo instead.
